config/routes.rb
Assetmanagement::Application.routes.draw do

  resources :options

  match 'genxlsx' => 'items#genxlsx'
  match 'genranddata' => 'options#genranddata'
  resources :itypes

  resources :locations

  resources :sites

  resources :items

  root :to =>  "home#index"

end

app/models/option.rb
class Option < ActiveRecord::Base
  attr_accessible :assettag
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
require 'ffaker'
  # GET /options
  # GET /options.json
  #
  def genranddata
  
  #Declare instance for render
  @options = Option.all

   n=500 + 1
   n.times do
     

     Location.create(:name => Faker::Address.city)
     Site.create(:name => Faker::AddressUS.state)
     Itype.create(:name => Faker::Product.product_name)
     
     @item = Item.new
     @item.serial = Faker::Product.model
     @item.site_id = rand(500) + 1
     @item.location_id = rand(500) + 1
     @item.itype_id = rand(500) + 1
     @item.save
   
   end
  
   #Send browser to items controller index view
   redirect_to items_url
  
  end

  def index
    @options = Option.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @options }
    end
  end

  # GET /options/1
  # GET /options/1.json
  def show
    @option = Option.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/new
  # GET /options/new.json
  def new
    @option = Option.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @option }
    end
  end

  # GET /options/1/edit
  def edit
    @option = Option.find(params[:id])
  end

  # POST /options
  # POST /options.json
  def create
    @option = Option.new(params[:option])

    respond_to do |format|
      if @option.save
        format.html { redirect_to @option, notice: 'Option was successfully created.' }
        format.json { render json: @option, status: :created, location: @option }
      else
        format.html { render action: "new" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /options/1
  # PUT /options/1.json
  def update
    @option = Option.find(params[:id])

    respond_to do |format|
      if @option.update_attributes(params[:option])
        format.html { redirect_to @option, notice: 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option = Option.find(params[:id])
    @option.destroy

    respond_to do |format|
      format.html { redirect_to options_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_form.html.erb
<%= form_for(@option) do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :assettag %><br />
    <%= f.text_field :assettag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing option</h1>

<%= render 'form' %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<h1>Listing options</h1>

<table>
  <tr>
    <th>Assettag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @options.each do |option| %>
  <tr>
    <td><%= option.assettag %></td>
    <td><%= link_to 'Show', option %></td>
    <td><%= link_to 'Edit', edit_option_path(option) %></td>
    <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'Generate Random Data', genranddata_path %>
<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<h1>New option</h1>

<%= render 'form' %>

<%= link_to 'Back', options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Assettag:</b>
  <%= @option.assettag %>
</p>


<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>