config/routes.rb
Assetmanagement::Application.routes.draw do

  resources :options

  match 'genxlsx' => 'items#genxlsx'
  match 'genranddata' => 'options#genranddata'
  resources :itypes

  resources :locations

  resources :sites

  resources :items

  root :to =>  "home#index"

end

app/controllers/itypes_controller.rb
class ItypesController < ApplicationController
  # GET /itypes
  # GET /itypes.json
  def index
    @itypes = Itype.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @itypes }
    end
  end

  # GET /itypes/1
  # GET /itypes/1.json
  def show
    @itype = Itype.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @itype }
    end
  end

  # GET /itypes/new
  # GET /itypes/new.json
  def new
    @itype = Itype.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @itype }
    end
  end

  # GET /itypes/1/edit
  def edit
    @itype = Itype.find(params[:id])
  end

  # POST /itypes
  # POST /itypes.json
  def create
    @itype = Itype.new(params[:itype])

    respond_to do |format|
      if @itype.save
        format.html { redirect_to @itype, notice: 'Itype was successfully created.' }
        format.json { render json: @itype, status: :created, location: @itype }
      else
        format.html { render action: "new" }
        format.json { render json: @itype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /itypes/1
  # PUT /itypes/1.json
  def update
    @itype = Itype.find(params[:id])

    respond_to do |format|
      if @itype.update_attributes(params[:itype])
        format.html { redirect_to @itype, notice: 'Itype was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @itype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itypes/1
  # DELETE /itypes/1.json
  def destroy
    @itype = Itype.find(params[:id])
    @itype.destroy

    respond_to do |format|
      format.html { redirect_to itypes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/itypes_helper.rb
module ItypesHelper
end

app/views/itypes/_form.html.erb
<%= form_for(@itype) do |f| %>
  <% if @itype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@itype.errors.count, "error") %> prohibited this itype from being saved:</h2>

      <ul>
      <% @itype.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/itypes/edit.html.erb
<h1>Editing itype</h1>

<%= render 'form' %>

<%= link_to 'Show', @itype %> |
<%= link_to 'Back', itypes_path %>

app/views/itypes/index.html.erb
<h1>Listing itypes</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @itypes.each do |itype| %>
  <tr>
    <td><%= itype.name %></td>
    <td><%= link_to 'Show', itype %></td>
    <td><%= link_to 'Edit', edit_itype_path(itype) %></td>
    <td><%= link_to 'Destroy', itype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Itype', new_itype_path %>

app/views/itypes/new.html.erb
<h1>New itype</h1>

<%= render 'form' %>

<%= link_to 'Back', itypes_path %>

app/views/itypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @itype.name %>
</p>


<%= link_to 'Edit', edit_itype_path(@itype) %> |
<%= link_to 'Back', itypes_path %>