config/routes.rb
Assetmanagement::Application.routes.draw do

  resources :options

  match 'genxlsx' => 'items#genxlsx'
  match 'genranddata' => 'options#genranddata'
  resources :itypes

  resources :locations

  resources :sites

  resources :items

  root :to =>  "home#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :site
  belongs_to :location
  belongs_to :itype
  validates :site_id, :location_id, :itype_id, :presence => true
  attr_accessible :serial, :stockable, :site_id, :location_id, :itype_id
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
require 'axlsx'
  
  def genxlsx

  p = Axlsx::Package.new
  wp = p.workbook
  items = Item.all
  wp.add_worksheet(:name=> "Inventory") do |sheet|
    sheet.add_row ["Serial", "Site", "Location", "Stockable", "Type"]
    items.each do |item|
      sheet.add_row [item.serial, item.site.name, item.location.name, item.stockable, item.itype.name]
    end
  end
     p.serialize("inventory.xlsx")
     send_file './inventory.xlsx', :type=> 'text/plain', :x_sendfile=>true
  end
  
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :serial %><br />
    <%= f.text_field :serial %>
  </div>
  <div class="field">
    <%= f.label :site_id %><br />
<%= collection_select(:item, :site_id, Site.all, :id, :name, :prompt => true) %>
<%= link_to 'New Site', new_site_path %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br />

<%= collection_select(:item, :location_id, Location.all, :id, :name, :prompt => true) %>
<%= link_to 'New Location', new_location_path %>
</div>
  <div class="field">
    <%= f.label :itype_id %><br />
<%= collection_select(:item, :itype_id, Itype.all, :id, :name, :prompt => true) %>
<%= link_to 'Item Type', new_itype_path %>
  </div>
  <div class="field">
    <%= f.label :stockable %><br />
    <%= f.check_box :stockable %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Serial</th>
    <th>Site</th>
    <th>Location</th>
    <th>Stockable</th>
    <th>Itype</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.serial %></td>
    <td><%= item.site.name %></td>
    <td><%= item.location.name %></td>
    <td><%= item.stockable %></td>
    <td><%= item.itype.name %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'Generate XLSX', genxlsx_path, :confirm => "Generate XLSX?" %>
<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Serial:</b>
  <%= @item.serial %>
</p>

<p>
  <b>Site:</b>
  <%= @item.site.name %>
</p>

<p>
  <b>Location:</b>
  <%= @item.location.name %>
</p>

<p>
  <b>Stockable:</b>
  <%= @item.stockable %>
</p>

<p>
  <b>Itype:</b>
  <%= @item.itype.name %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>